### ISSUE TITLE
db server closed the connection.

### ISSUE THREAD

**Issue by BoChao-Hsu** [soruly/sola#11]
hi , there I am  again,when i run : npm run load ,  show this info:
`
Connecting to mariadb
Connecting to amqp server
Waiting for messages in load_hash. To exit press CTRL+C
Received load_hash job for 76522/normal.mp4
Loading /mnt/data/anime_hash/76522/normal.mp4.xml.xz into solr
Unzipping files
Parsing xml

db error { Error: Connection lost: The server closed the connection.
    at Protocol.end (/usr/sola/node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (/usr/sola/node_modules/mysql/lib/Connection.js:97:28)
    at Socket.<anonymous> (/usr/sola/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) fatal: true, code: 'PROTOCOL_CONNECTION_LOST' }

`

**Comment by soruly** [comment]
I can't reproduce this issue. I think something is wrong in your mariaDB database connection. Try clearing all docker volumes and try again?

**Comment by soruly** [comment]
Another potential issue would be native nodejs modules incompatible with mariaDB, if you upgraded nodejs recently try reinstalling node_modules?

**Comment by soruly** [comment]
It seems this error message would appear when the loader/hasher worker is idle for a few minutes, but it would still be able to connect to mariaDB when it receive new jobs. I'll check if the db connection is closed properly :|
