### ISSUE TITLE
npm run create-core error

### ISSUE THREAD

**Issue by tiaxter** [soruly/sola#68]
Followed the README.md. 
```
[jerry@localhost sola]$ npm run create-core
sola@0.5.0 create-core /home/jerry/sola
node src/create-core.js

Check if solr core lire_0 already loaded
(node:6674) UnhandledPromiseRejectionWarning: FetchError: request to http://127.0.0.1:8983/solr/admin/cores?wt=json failed, reason: connect ECONNREFUSED 127.0.0.1:8983
    at ClientRequest.<anonymous> (/home/jerry/sola/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:6674) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6674) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by soruly** [comment]
Can you open 127.0.0.1:8983 from web browser?

**Comment by tiaxter** [comment]
Nope, I can't

**Comment by soruly** [comment]
I think there's something wrong with docker-compose, can you look into the logs of the docker containers?
